import { getPrisma } from '../client';

// Database-backed session store: persistent across restarts, server-enforced expiry,
// and revocable (logout, password change, disable). The session id is a high-entropy
// opaque value generated by the caller; only hashes of UA/IP are stored.

export interface DbSession {
  id: string;
  userId: string;
  createdAt: Date;
  expiresAt: Date;
  revokedAt: Date | null;
}

export async function createSession(input: {
  id: string; userId: string; expiresAt: Date; userAgentHash?: string | null; ipHash?: string | null;
}): Promise<void> {
  await getPrisma().session.create({
    data: {
      id: input.id, userId: input.userId, expiresAt: input.expiresAt,
      userAgentHash: input.userAgentHash ?? null, ipHash: input.ipHash ?? null,
    },
  });
}

export async function findById(id: string): Promise<DbSession | null> {
  return (await getPrisma().session.findUnique({
    where: { id },
    select: { id: true, userId: true, createdAt: true, expiresAt: true, revokedAt: true },
  })) as DbSession | null;
}

export async function revoke(id: string): Promise<void> {
  // Only revoke if present and not already revoked; ignore missing.
  await getPrisma().session.updateMany({ where: { id, revokedAt: null }, data: { revokedAt: new Date() } });
}

export async function revokeAllForUser(userId: string): Promise<void> {
  await getPrisma().session.updateMany({ where: { userId, revokedAt: null }, data: { revokedAt: new Date() } });
}

export async function touch(id: string): Promise<void> {
  await getPrisma().session.updateMany({ where: { id, revokedAt: null }, data: { lastSeenAt: new Date() } });
}
